language: objective-c
osx_image: xcode8
before_install:
  - gem install xcpretty
script:
  - cd Examples
  - xcodebuild -version
  - xcodebuild -project DynamicColorExample.xcodeproj -scheme iOSTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES test
  - bash <(curl -s https://codecov.io/bash) -cF ios -J '^DynamicColor$'
  - xcodebuild -project DynamicColorExample.xcodeproj -scheme OSXTests -sdk macosx -configuration Release GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES test
  - bash <(curl -s https://codecov.io/bash) -cF osx -J '^DynamicColor$'
